name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Execute SSH commmands on remote server
      uses: girigowda/ci-cd1@master
      with:
        hosts: 'ubuntu@13.232.240.3'
        privateKey: ${{ secrets.KEY }}
        debug: false
        command: |
          ls -ltr
          ssh app
          pwd
          ls -ltr

