name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: | 
        ls
        pwd
        cd /home/krunal/Music/frontend
        git pull
        ls
        pwd
        
