name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      uses: server/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ubuntu
        password: ${{ secrets.KEY }}
    - name:  find oath    
      run: | 
        pwd

        
