name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: | 
        git pull "https://girishgowda:girigowda1@gitlab.com/dataphion/aitester/frontend.git"
